# Generated by Django 2.2.13 on 2020-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastorroast',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='boastorroast',
            name='down_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='boastorroast',
            name='up_votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
