# Generated by Django 2.2.13 on 2020-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0003_remove_boastorroast_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastorroast',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boastorroast',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
